---
title: "TT_2024_06_04"
format: html
editor: visual
---

## Loading

```{r}
library(tidytuesdayR)
library(dplyr)
library(ggplot2)
tuesdata <- tidytuesdayR::tt_load('2024-06-04')

td<-tuesdata$cheeses
```

## Exploration

```{r}
table(td$country)

single_country<-td%>%
  filter(!grepl(",", country))%>%
  filter(!grepl(" and ", country))%>%#spaces necessary to not hit _land
  filter(country!="United Kingdom")

table(single_country$country)
table(single_country$country)%>%table()

bigger_country<-single_country%>%
  group_by(country)%>%
  filter(n()>=30)%>%
  ungroup()

table(bigger_country$country)

td$flavor%>%stringr::str_split(", ")%>%unlist()%>%table(useNA = "a")

table(td$family,useNA = "a")
table(td$milk,useNA = "a")
table(td$color,useNA = "a")
table(td$type,useNA = "a")
```

## Fig 1: Language

```{r}
cleaned_country<-td%>%
  transmute(
    country_old=country,
    country=case_when(
      is.na(country)~"Stateless Cheese",
      country=="United Kingdom"~"GB: UK",
      #country=="Ireland"~"GB: Ireland",
      country=="Scotland"~"GB: Scotland",
      country=="Great Britain"~"GB: GB",
      country=="Wales"~"GB: Wales",
      country=="England"~"GB: England",
      country%in%c(
        "England, Great Britain, United Kingdom",
        "England, Scotland, United Kingdom",
        "England, Scotland, Wales",
        "England, United Kingdom",
        "Great Britain, Scotland, United Kingdom",
        "Great Britain, United Kingdom, Wale",
        "Scotland, United Kingdom",
        "United Kingdom, Wales"
      )~"GB: Multiple",
      grepl(",", country)~"Multiple Countries",
      grepl(" and ", country)~"Multiple Countries",
      TRUE~country
    )
  )%>%
  group_by(country)%>%
  mutate(
    country=case_when(
      grepl("GB: ",country)~country,#keep all these
      n()<3~"Rare Countries",
      TRUE~country
    )
  )%>%
  bind_rows(
      eval(.)%>%
        filter(grepl("GB: ",country))%>%
        mutate(country='Great Britain(Total)')
      )%>%
  mutate(
    group=case_when(
      grepl("GB: ",country)~"Subsets simplified into 'Great Britain(Total)'",
      country%in%c(
        "Australia","Canada","Great Britain(Total)", "New Zealand", "Ireland", "United States"
      )~"(Mostly) English-speaking",
      country%in%c("Brazil","India","Mexico")~"Rest of World",
      country%in%c("Rare Countries", "Stateless Cheese", "Multiple Countries")~"Special Cases",
      TRUE~"No English, Europe"
    )
  )

for_order<-cleaned_country%>%
  group_by(country)%>%
  summarize(n=n(), group=first(group))
#n_gb<-for_order%>%filter(country=="Total GB")%>%pull(n) #retired
for_order<-for_order%>%
  mutate(
    fake_n_for_order=case_when(
      grepl("GB: ",country)~-1,
      group=="Special Cases"~0,
      TRUE~n
    )
  )%>%
  arrange(-fake_n_for_order,-n)%>%
  pull(country)

to_plot1<-cleaned_country%>%
  mutate(
    group=factor(group,levels=c(
      "(Mostly) English-speaking",
      "Subsets simplified into 'Great Britain(Total)'",
      "No English, Europe",
      "Special Cases",
      "Rest of World"
    )),
    country=factor(country,levels=for_order),
    for_outline=case_when(
      grepl("GB: ",country)~TRUE,
      TRUE~FALSE
      )
    )

fig1<-(to_plot1%>%
  ggplot(
    aes(
      x=country,
      fill=group,
      #col=for_outline
      )
    )+
  geom_bar()+
  scale_fill_discrete(
    NULL,
    type=c("darkblue","gray90","lightblue","grey30","purple")
    )+
  #scale_color_discrete(type=c("white","darkblue"))+
  guides(
    #color="none",
    fill=guide_legend(nrow=2,position = "bottom")
    )+
  theme_minimal()+
  theme(
    axis.text.x=element_text(angle = -40, hjust = 0),
    panel.grid.major.x  = element_blank(),
    plot.margin = unit(c(5.5,60,5.5,5.5),"pt")
    )+
  scale_y_continuous("Number of Distinct Cheeses in Database")+
  scale_x_discrete(NULL)+
  ggtitle("Language Bias in the Cheese.com Database #TidyTuesday")+
  annotate(
    "label", 
    x="Multiple Countries",
    y = 290, 
    label = "Supporting Anecdote: Author is Swiss and can confirm\nthat most of their family's local favourites are missing",
    fill="grey90"
    )+
  annotate(
    "label", 
    x="Multiple Countries",
    y = 250, 
    label = "The country assignment within Great Britain was messy and\n the region is thus included both as summarized total and by subset",
    fill="grey90"
    ))+
  coord_cartesian(clip = "off",expand = FALSE,ylim=c(0,315))

ggsave(
  plot = fig1,
  device = "pdf",
  units = "cm",
  width = 20,
  height = 17,
  filename = "fig1_06_04.pdf")
```

## Fig 2 Taste

Concept: Take tastes per cheese with enough mentions and create flow diagram
