---
title: "TT_2024_11_12"
format: html
editor: visual
---

## Loading and Preparation

```{r}
library(tidytuesdayR)
library(dplyr)
library(ggplot2)

tuesdata <- tidytuesdayR::tt_load('2024-11-26')

main<-tuesdata$cbp_resp
main2<-tuesdata$cbp_state

for_fig<-main%>%
  transmute(
    country=citizenship,
    counter=encounter_count,
    year=fiscal_year,
    month=month_abbv, 
    region=land_border_region
  )%>%
  bind_rows(
    main2%>%
      transmute(
        country=citizenship,
        counter=encounter_count,
        year=fiscal_year,
        month=month_abbv, 
        region=land_border_region
      )
  )%>%
  filter(month=="APR")%>%
  filter(year=="2023")%>%
  group_by(country,region)%>%
  summarize(counter=sum(counter))%>%
  ungroup()%>%
  arrange(counter)%>%
  mutate(
    country=case_when(
      country=="CHINA, PEOPLES REPUBLIC OF"~"CHINA",
      country=="MYANMAR (BURMA)"~"MYANMAR",
      TRUE~country
    )
  )

order=c("OTHER",
        for_fig%>%
          filter(country!="OTHER")%>%
          group_by(country)%>%
          summarize(n=sum(-counter))%>%
          ungroup()%>%
          arrange(n)%>%
          pull(country)
        )

for_fig<-for_fig%>%
  mutate(
    country=factor(country,levels=order),
    region=case_when(
      region=="Other"~"Air and Sea",
      region=="Northern Land Border"~"Northern Border",
      TRUE~"Southern Border"
    )%>%factor(levels = c("Northern Border","Southern Border", "Air and Sea"))
  )

manual_x=data.frame(country=order,x=c(1,3:23))

for_fig<-for_fig%>%left_join(manual_x)
```

## Plotting

```{r}
fig<-for_fig%>%
  ggplot(aes(x=x,y=counter))+
  geom_bar(stat = "identity",col="white")+
  facet_grid(rows = vars(region))+
  scale_y_continuous(
    "Individuals encountered in April 2023",
    trans="log",
    breaks = c(500,1000,5000,10000,50000),
    labels = c(500,1000,5000,10000,50000),
    minor_breaks = NULL
    )+
  scale_x_continuous(
    NULL,
    breaks=manual_x$x,
    labels=manual_x$country,
    minor_breaks = NULL
    )+
  coord_cartesian(ylim=c(300,75000),expand = FALSE,xlim = c(0.4,23.6))+
  theme_light()+
  labs(
    title = "A Month of the US's Customs and Border Protection   #TidyTuesday",
    subtitle = "What struck me in this data is the wealth of 'Other'-entries\nWhat determines which countries do not get to be anonymous?\nIt's hard to imagine the 50'000-strong 'Other' doesn't include nations that dwarf Romania's number\n\n(Y-Axis cuts off at 300 and 75'000 to declutter and zoom the figure)"
    )+
  theme(
    plot.background = element_rect(fill="#F0E9D6"),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(angle=60,vjust = 0.62)
  )

ggsave(
  plot = fig,
  device = "png",
  dpi=300,
  units = "cm",
  width = 23,
  height = 14,
  filename = "fig_11_26.png")
```
